runtime: python37
entrypoint: gunicorn -b :$PORT "CAWPr:create_app()" --timeout 900
instance_class: F4
env_variables:
    GOOGLE_CLOUD_BUCKET: "cawp-47548.appspot.com"
    REMOTE_BLOB_NAME: "testGAE" 
    INSTANCE_CONNECION_NAME: "cawp-47548:us-east4:testsql"
    DATABASE_USERNAME: "postgres"
    DATABASE_PASSWORD: "Maccabi01"
    DATABASE_NAME: "postgres"
    DATABASE_HOST: "/cloudsql/cawp-47548:us-east4:testsql"
