name: CAWP
channels:
    - fastai
    - pytorch
    - conda-forge
    - anaconda
dependencies:
    - python=3.7
    - fastai=2.0.13
    - flask
    - fastcore=1.0.12
    - python-dotenv
    - watchdog
    - scrapy
    - html2text
    - gunicorn
    - psycopg2
    - google-cloud-storage
    - git
    - postgresql
    - google-cloud-sdk
    - spacy=2.3.1
    - pip=20.1.1
